/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tsbtool_gui;

/**
 *
 * @author Chris
 */
public class TSBToolAppletPanel extends javax.swing.JPanel
{

    /**
     * Creates new form TSBToolAppletPanel
     */
    public TSBToolAppletPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mLaunchButton = new javax.swing.JButton();
        mLaunchFormButton = new javax.swing.JButton();
        mFormTextField = new javax.swing.JTextField();

        mLaunchButton.setText("Launch TSBToolSupreme");
        mLaunchButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                mLaunchButtonMouseClicked(evt);
            }
        });

        mLaunchFormButton.setText("Launch other Form");
        mLaunchFormButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                mLaunchFormButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mLaunchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mLaunchFormButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mFormTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mLaunchButton)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLaunchFormButton)
                    .addComponent(mFormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mLaunchButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_mLaunchButtonMouseClicked
    {//GEN-HEADEREND:event_mLaunchButtonMouseClicked
        MainGUI form = new MainGUI();
        form.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        form.setVisible(true);
        
    }//GEN-LAST:event_mLaunchButtonMouseClicked

    private void mLaunchFormButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_mLaunchFormButtonMouseClicked
    {//GEN-HEADEREND:event_mLaunchFormButtonMouseClicked
        String text = mFormTextField.getText();
        
        switch(text)
        {
            case "ColorForm":
                ColorForm colorForm = new ColorForm(null, true);
                colorForm.setVisible(true);
                colorForm.dispose();
                break;
        }   
    }//GEN-LAST:event_mLaunchFormButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField mFormTextField;
    private javax.swing.JButton mLaunchButton;
    private javax.swing.JButton mLaunchFormButton;
    // End of variables declaration//GEN-END:variables
}
